services:
  - type: web
    name: short-backgammon
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app.server:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
